### ISSUE TITLE
Is this ongoing course?

### ISSUE THREAD

**Issue by epikjjh** [Gaon-Choi/ELE3077#1]
Hi, I'm just surfing several repos and found out some are the ongoing course's ones.
It might be a bit of an obsession, but AFAIK you might get hijacked your codes unless you turn this repo into private...
No offense at all 🙏

**Comment by Gaon-Choi** [comment]
I think this is not a big problem, because the instructor allowed us to post our code in Github. Thank you for your consideration anyway :) If you're interested in signal processing, this repository and ELE3076(Digital Signal Processing I) will be helpful!
